security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        fos_twitter:
            id: zeega.twitter.user
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:    ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: /dashboard
                use_forward: true
                check_path: fos_user_security_check
            fos_twitter:
                check_path: ZeegaSocialBundle_twitter_login_check
                default_target_path: /dashboard
                provider: fos_twitter
            logout:
                path:   /logout
                target: /
            anonymous: true     # default is to allow anonymous access to everything

    access_control:
        - { path: ^/[0-9]+, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http }    # force http for project playback
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }   # force https for login
        - { path: ^/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY}                       # this needs to be here; not sure why
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/dashboard, role: ROLE_USER }
        - { path: ^/library, role: ROLE_USER }
        - { path: ^/editor/, role: ROLE_USER }
        - { path: ^/widget, role: ROLE_USER, requires_channel: https }
        - { path: ^/js/lib, role: ROLE_USER, requires_channel: https }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http }