fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_register_mobile:
    pattern: /m/register
    defaults: { _controller:  ZeegaUserBundle:Registration:register, mobile:"1" }

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

_security_logout:
    pattern:  /logout    


_security_login:
    pattern:  /login
    defaults: { _controller:  ZeegaUserBundle:Security:login }

_security_check:
    pattern:  /login_check

fos_user_registration_success:
    pattern:  /register/success/
    defaults: { _controller:  ZeegaUserBundle:Registration:success }

