parameters:
#    zeega_user.example.class: Zeega\UserBundle\Example

services:
    zeega_user_registration.form.type:
        class: Zeega\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: zeega_user_registration}
    zeega_user.form.handler.registration:
        class: Zeega\UserBundle\Form\Handler\RegistrationFormHandler
        arguments: ["@fos_user.registration.form", "@request", "@fos_user.user_manager", "@fos_user.mailer", "@service_container"]
        scope: request
        public: false
    zeega_user.form.handler.resetting:
        class: Zeega\UserBundle\Form\Handler\ResettingFormHandler
        arguments: ["@fos_user.resetting.form", "@request", "@fos_user.user_manager"]
        scope: request
        public: false
