# src/Zeega/EditorBundle/Resources/config/doctrine/Frame.orm.yml
Zeega\DataBundle\Entity\Frame:
   type: entity
   table: frame
   repositoryClass: Zeega\DataBundle\Repository\EditorRepository
   manyToOne:
    sequence:
     targetEntity: Sequence
     joinColumns:
       sequence_id:
        referencedColumnName: id
        onDelete: CASCADE
   id:
    id:
     type: integer
     generator: { strategy: AUTO }
   fields:
    sequence_index:
     type: integer
     length: 2
     nullable: true
    layers:
     type: array
     nullable: true
    attr:
     type: array
     nullable: true
    thumbnail_url:
     type: string
     length: 101
     nullable: true
    enabled:
     type: boolean
     nullable: true
 