# src/Zeega/\CoreBundle\/Resources/config/doctrine/Item.orm.yml
Zeega\DataBundle\Entity\Item:
    type: entity
    table: item
    repositoryClass: Zeega\DataBundle\Repository\ItemRepository
    lifecycleCallbacks:
       prePersist: [onPrePersist]
       preUpdate: [onPreUpdate]
    manyToMany:
        child_items: 
            targetEntity: Item
            inversedBy: parent_items
            onDelete: CASCADE
            cascade: ["persist"]
            joinTable:
                name: collection
                joinColumns:
                    id:
                        referencedColumnName: id
                inverseJoinColumns:
                    child_item_id:
                        referencedColumnName: id
        parent_items:
            targetEntity: Item
            mappedBy: child_items
            cascade: ["persist"]
    manyToOne:
        site:
            targetEntity: Zeega\DataBundle\Entity\Site
            cascade: ["persist"]
        user:
            targetEntity: Zeega\DataBundle\Entity\User
    id:
        id:
            type: bigint
            generator: { strategy: AUTO }
    fields:
        site_id:
            type: integer
            nullable: true            
        title:
            type: string
            length: 
            nullable: true
        user_id:
            type: integer
            nullable: false
        description:
            type: string
            length: 500
            nullable: true
        text:
            type: text
            nullable: true
        uri:
            type: string
            length: 500
            unique: false
        attribution_uri:
            type: string
            length: 500
        date_created:
            type: datetime
            nullable: true
        date_updated:
            type: datetime
            nullable: true
        archive:
            type: string
            length: 50
            nullable: false
        media_type:
            type: string
            length: 20
            nullable: false
        layer_type:
            type: string
            length: 20
            nullable: false        
        thumbnail_url:
            type: string
            length: 500
            nullable: true
        child_items_count:
            type: integer
            nullable: false
            default: default 0
        media_geo_latitude:
            type: float
            length: 10
            nullable: true
        media_geo_longitude:
            type: float
            length: 10
            nullable: true
        location:
            type: string
            length: 100
            nullable: true
        media_date_created:
            type: datetime
            nullable: true
        media_date_created_end:
            type: datetime
            nullable: true        
        media_creator_username:
            type: string
            length: 80
            nullable: false
        media_creator_realname:
            type: string
            length: 80
            nullable: true
        media_creator_realname:
            type: string
            length: 80
            nullable: true
        license:
            type: string
            length: 50
            nullable: true
        attributes:
            type: array
            nullable: true
        tags:
            type: array
            nullable: true
        enabled:
            type: boolean
            nullable: false
        published:
            type: boolean
            nullable: false
        indexed:
            type: boolean
            nullable: true
        geo_latlng:
            type: string
            nullable: true
        
    indexes:
        media_date_created_index:
            columns: [media_date_created]      
        media_date_created_end_index:
            columns: [media_date_created_end]      
        item_type_index:
            columns: [layer_type]
        media_type_index:
            columns: [media_type]
        item_indexed_index:
            columns: [indexed]        
        site_id_index:
            columns: [site_id]
        item_enabled_index:
            columns: [enabled]
        item_text_index:
            columns: [text]
        item_description_index:
            columns: [description]