# src/Zeega/\CoreBundle\/Resources/config/doctrine/Item.orm.yml
Zeega\DataBundle\Entity\Item:
    type: entity
    table: item
    repositoryClass: Zeega\DataBundle\Repository\ItemRepository
    lifecycleCallbacks:
       prePersist: [onPrePersist]
    manyToMany:
        child_items: 
            targetEntity: Item
            inversedBy: parent_items
            onDelete: CASCADE
            cascade: ["persist"]
            joinTable:
                name: collection
                joinColumns:
                    id:
                        referencedColumnName: id
                inverseJoinColumns:
                    child_item_id:
                        referencedColumnName: id
        parent_items:
            targetEntity: Item
            mappedBy: child_items
            cascade: ["persist"]
    manyToOne:
        user:
            targetEntity: Zeega\DataBundle\Entity\User
    id:
        id:
            type: bigint
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 
            nullable: true
        user_id:
            type: integer
            nullable: false
        description:
            type: string
            length: 500
            nullable: true
        text:
            type: text
            nullable: true
        uri:
            type: string
            length: 500
            unique: false
        attribution_uri:
            type: string
            length: 500
        date_created:
            type: datetime
            nullable: true
        date_updated:
            type: datetime
            nullable: true
        archive:
            type: string
            length: 50
            nullable: false
        media_type:
            type: string
            length: 20
            nullable: false
        layer_type:
            type: string
            length: 20
            nullable: false        
        thumbnail_url:
            type: string
            length: 500
            nullable: true
        child_items_count:
            type: integer
            nullable: false
            default: default 0
        media_geo_latitude:
            type: float
            length: 10
            nullable: true
        media_geo_longitude:
            type: float
            length: 10
            nullable: true
        location:
            type: string
            length: 100
            nullable: true
        media_date_created:
            type: datetime
            nullable: true
        media_creator_username:
            type: string
            length: 80
            nullable: false
        media_creator_realname:
            type: string
            length: 80
            nullable: true
        media_creator_realname:
            type: string
            length: 80
            nullable: true
        license:
            type: string
            length: 50
            nullable: true
        attributes:
            type: array
            nullable: true
        tags:
            type: array
            nullable: true
        id_at_source:
            type: string
            length: 50
            nullable: true
        enabled:
            type: boolean
            nullable: false
        published:
            type: boolean
            nullable: false
        geo_latlng:
            type: string
            nullable: true
        ingested_by: 
            type: string
            length: 15
            nullable: true
        duration:
            type: integer
            length: integer
            nullable: true

    indexes:
        media_date_created_index:
            columns: [media_date_created]
        item_type_index:
            columns: [layer_type]
        item_enabled_index:
            columns: [enabled]
        item_description_index:
            columns: [description]
        item_attribution_uri_index:
            columns: [attribution_uri]
        item_uri_index:
            columns: [uri]
        item_ingested_by_index:
            columns: [ingested_by]
