# src/Zeega/EditorBundle/Resources/config/doctrine/Layer.orm.yml
Zeega\DataBundle\Entity\Layer:
    type: entity
    table: layer
    repositoryClass: Zeega\DataBundle\Repository\LayerRepository
    manyToOne:
        item:
            targetEntity: Zeega\DataBundle\Entity\Item
        project:
            targetEntity: Zeega\DataBundle\Entity\Project
    manyToMany:
        sequences:
            targetEntity: Zeega\DataBundle\Entity\Sequence
            mappedBy: layers
        frames:
            targetEntity: Zeega\DataBundle\Entity\Frame
            mappedBy: layers
    id:
        id:
            type: bigint
            generator: { strategy: AUTO }
    fields:
        type:
            type: string
            length: 50
            nullable: true
        text:
            type: string
            length: 1000
            nullable: true
        attr:
            type: array
            nullable: true
        