# src/Zeega/EditorBundle/Resources/config/doctrine/Project.orm.yml
Zeega\DataBundle\Entity\Project:
    type: entity
    table: project
    cascade: remove
    repositoryClass: Zeega\DataBundle\Repository\ProjectRepository
    manyToMany:
        users:
            targetEntity: Zeega\DataBundle\Entity\User
            inversedBy:
                name: projects
            joinTable:
                name: project_users
                joinColumns:
                    project_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    user_id:
                        referencedColumnName: id
    manyToOne:
        site:
            targetEntity: Site
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        item_id:
            type: string
            length: 255
            nullable: true
        title:
            type: string
            length: 255
            nullable: true
        description:
            type: string
            length: 1024
            nullable: true
        location:
            type: string
            length: 255
            nullable: true
        tags:
            type: array
            nullable: true        
        enabled:
            type: boolean
            nullable: false
        published:
            type: boolean
            nullable: false
        authors:
            type: string
            length: 255
            nullable: true
        cover_image:
            type: string
            length: 255
            nullable: true
        estimated_time:
            type: string
            length: 140
            nullable: true  
        date_created:
            type: datetime
            nullable: false      
        date_updated:
            type: datetime
            nullable: true
        date_published:
            type: datetime
            nullable: true
        
    indexes:
        project_enabled_index:
            columns: [enabled]
        project_date_updated:
            columns: [date_updated]
 
