projects:
  type:     rest
  resource: Zeega\CoreBundle\Controller\ProjectsController

sequences:
  type:     rest
  resource: Zeega\CoreBundle\Controller\SequencesController

layers:
  type:     rest
  resource: Zeega\CoreBundle\Controller\LayersController

sites:
  type:     rest
  resource: Zeega\CoreBundle\Controller\SitesController
  
ZeegaCoreBundle_home:
    pattern: /
    defaults: { _controller:  ZeegaCoreBundle:Editor:home }

ZeegaCoreBundle_site:
    pattern: /site/{short}
    defaults: { _controller:  ZeegaCoreBundle:Editor:site }

ZeegaCoreBundle_editor:
    pattern: /site/{short}/project/{id}
    defaults: { _controller:  ZeegaCoreBundle:Editor:editor }
    
ZeegaCoreBundle_browser:
    pattern: /site/{short}/browser
    defaults: { _controller:  ZeegaCoreBundle:Editor:browser }

ZeegaCoreBundle_faq:
    pattern: /faq
    defaults: { _controller:  ZeegaCoreBundle:Editor:faq }
    
ZeegaCoreBundle_embed:
    pattern: /{id}
    defaults: { _controller:  ZeegaCoreBundle:Publish:embed }

ZeegaCoreBundle_badbrowser:
    pattern: /browser/notsupported
    defaults: { _controller:  ZeegaCoreBundle:BadBrowser:index }

ZeegaCoreBundle_frame_publish:
    pattern: /frame/{id}/view
    defaults: { _controller:  ZeegaCoreBundle:Publish:frame }

ZeegaCoreBundle_project_publish:
    pattern: /project/{id}/view
    defaults: { _controller:  ZeegaCoreBundle:Publish:project }

ZeegaCoreBundle_collection_publish:
    pattern: /collection/{id}/view
    defaults: { _controller:  ZeegaCoreBundle:Publish:collection }