parameters:
#    zeega_core.example.class: Zeega\CoreBundle\Example

services:
    zeega_user.registration.form.type:
        class: Zeega\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: zeega_user_registration }